### ISSUE TITLE
Do you have the implementation code of "Path Integral Guided Policy Search"

### ISSUE THREAD

**Issue by dujinyu** [tttor/rl-foundation#1]
Do you have the implementation code of "Path Integral Guided Policy Search"

**Comment by tttor** [comment]
No, I do not have.

**Comment by dujinyu** [comment]
Thank you anyway.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Vektor Dewanto"<notifications@github.com&gt;; 
发送时间: 2019年11月6日(星期三) 凌晨5:00
收件人: "tttor/rl-foundation"<rl-foundation@noreply.github.com&gt;; 
抄送: "1242642280"<1242642280@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [tttor/rl-foundation] Do you have the implementation code of &quot;Path Integral Guided Policy Search&quot; (#1)




No, I do not have.
